image: ambientum/php:7.0-nginx

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
  - ambientum/mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: schedulerapp-test
  MYSQL_DATABASE: schedulerapp-test
  MYSQL_USER: schedulerapp-test
  MYSQL_PASSWORD: schedulerapp-test  
  
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - vendor/
  - node_modules/

before_script:
  # Install project dependencies.
  - composer install --prefer-dist --no-ansi --no-interaction
  - cp .env.testing .env
  
  # Generate an application key.
  - php artisan key:generate
  
  # Copy .env with the new application key to .env.testing
  - cp -f .env .env.testing
  
  # Re-cache.
  - php artisan config:clear

  # Run database migrations.
  - php artisan migrator
  
test:
  script:
  # run laravel tests
  - php vendor/bin/phpunit -v --coverage-text --colors=always --stderr --coverage-xml build/coverage-xml/ 
  
after_script:
  - php vendor/bin/codacycoverage phpunit
